/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32CubeIDE Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <sys/stat.h>
#include <stdlib.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>
#include <stdint.h>

/* ── Wall-clock time support ──────────────────────────────────────────────
 * _gettimeofday() returns real wall-clock time once an epoch has been set
 * via _settimeofday_epoch().  Until then, returns {0,0}.
 *
 * The epoch is stored together with the FreeRTOS tick count at the moment
 * it was captured, allowing _gettimeofday() to extrapolate the current
 * time from the tick delta.
 * ────────────────────────────────────────────────────────────────────────── */
static volatile uint32_t s_epoch_sec     = 0;   /* UTC seconds at capture   */
static volatile uint32_t s_epoch_usec    = 0;   /* microseconds at capture  */
static volatile uint32_t s_epoch_tick    = 0;   /* xTaskGetTickCount() at capture */
static volatile uint8_t  s_epoch_valid   = 0;

/* Weak import — FreeRTOS tick counter.  If FreeRTOS is not linked (unlikely
 * on this target) we fall back to tick=0 so _gettimeofday still works. */
extern uint32_t xTaskGetTickCount( void ) __attribute__((weak));

/* configTICK_RATE_HZ from FreeRTOSConfig.h — declare as extern so we don't
 * need to include FreeRTOS headers in this CubeIDE-generated file.          */
#ifndef configTICK_RATE_HZ
#define configTICK_RATE_HZ 1000U
#endif

/**
 * @brief Set the wall-clock epoch used by _gettimeofday().
 *
 * Called once from the SNTP sync code (sntp_port.c) after obtaining the
 * current UTC time from an NTP server.
 */
void _settimeofday_epoch( uint32_t sec, uint32_t usec )
{
    s_epoch_tick  = xTaskGetTickCount ? xTaskGetTickCount() : 0;
    s_epoch_usec  = usec;
    s_epoch_sec   = sec;
    s_epoch_valid = 1;
}


/* Variables */
extern int __io_putchar(int ch) __attribute__((weak));
extern int __io_getchar(void) __attribute__((weak));


char *__env[1] = { 0 };
char **environ = __env;


/* Functions */
void initialise_monitor_handles()
{
}

int _getpid(void)
{
  return 1;
}

int _kill(int pid, int sig)
{
  (void)pid;
  (void)sig;
  errno = EINVAL;
  return -1;
}

void _exit (int status)
{
  _kill(status, -1);
  while (1) {}    /* Make sure we hang here */
}

__attribute__((weak)) int _read(int file, char *ptr, int len)
{
  (void)file;
  int DataIdx;

  for (DataIdx = 0; DataIdx < len; DataIdx++)
  {
    *ptr++ = __io_getchar();
  }

  return len;
}

__attribute__((weak)) int _write(int file, char *ptr, int len)
{
  (void)file;
  int DataIdx;

  for (DataIdx = 0; DataIdx < len; DataIdx++)
  {
    __io_putchar(*ptr++);
  }
  return len;
}

int _close(int file)
{
  (void)file;
  return -1;
}


int _fstat(int file, struct stat *st)
{
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

int _isatty(int file)
{
  (void)file;
  return 1;
}

int _lseek(int file, int ptr, int dir)
{
  (void)file;
  (void)ptr;
  (void)dir;
  return 0;
}

int _open(char *path, int flags, ...)
{
  (void)path;
  (void)flags;
  /* Pretend like we always fail */
  return -1;
}

int _wait(int *status)
{
  (void)status;
  errno = ECHILD;
  return -1;
}

int _unlink(char *name)
{
  (void)name;
  errno = ENOENT;
  return -1;
}

int _times(struct tms *buf)
{
  (void)buf;
  return -1;
}

int _gettimeofday(struct timeval *tv, void *tzvp)
{
  (void)tzvp;

  if (tv != NULL)
  {
    if (s_epoch_valid)
    {
      uint32_t now_tick = xTaskGetTickCount ? xTaskGetTickCount() : 0;
      uint32_t delta_ticks = now_tick - s_epoch_tick;
      uint32_t delta_sec  = delta_ticks / configTICK_RATE_HZ;
      uint32_t delta_ms   = delta_ticks % configTICK_RATE_HZ;

      tv->tv_sec  = s_epoch_sec + delta_sec;
      tv->tv_usec = s_epoch_usec + delta_ms * 1000U;

      /* Carry microseconds → seconds */
      while (tv->tv_usec >= 1000000)
      {
        tv->tv_usec -= 1000000;
        tv->tv_sec++;
      }
    }
    else
    {
      tv->tv_sec  = 0;
      tv->tv_usec = 0;
    }
  }

  return 0;
}

int _stat(char *file, struct stat *st)
{
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

int _link(char *old, char *new)
{
  (void)old;
  (void)new;
  errno = EMLINK;
  return -1;
}

int _fork(void)
{
  errno = EAGAIN;
  return -1;
}

int _execve(char *name, char **argv, char **env)
{
  (void)name;
  (void)argv;
  (void)env;
  errno = ENOMEM;
  return -1;
}
