/*
 * config.h — libsrtp build configuration for STM32N6 (ARM Cortex-M55)
 *
 * Hand-crafted for bare-metal FreeRTOS with mbedTLS crypto backend.
 * Normally auto-generated by cmake or ./configure.
 *
 * SPDX-License-Identifier: MIT
 */

#ifndef SRTP_CONFIG_H
#define SRTP_CONFIG_H

/* ARM Cortex-M55 is a RISC architecture (slow unaligned byte access) */
#define CPU_RISC  1

/* Use mbedTLS as the crypto backend */
#define MBEDTLS   1

/* Enable AES-GCM (required for SRTP_PROFILE_AES128_CM_HMAC_SHA1_80) */
#define GCM       1

/* Standard C headers available in newlib */
#define HAVE_STDINT_H    1
#define HAVE_INTTYPES_H  1
#define HAVE_STDLIB_H    1

/* Standard integer types available */
#define HAVE_UINT8_T    1
#define HAVE_UINT16_T   1
#define HAVE_UINT32_T   1
#define HAVE_UINT64_T   1
#define HAVE_INT32_T    1

/* GCC supports inline */
#define HAVE_INLINE  1

/* sizeof(unsigned long) = 4 on ARM Cortex-M */
#define SIZEOF_UNSIGNED_LONG        4
/* sizeof(unsigned long long) = 8 */
#define SIZEOF_UNSIGNED_LONG_LONG   8

/* Little-endian target — do NOT define WORDS_BIGENDIAN */

/* Package identity strings (used by srtp_get_version_string / srtp_get_version) */
#define PACKAGE_STRING   "libsrtp 2.6.0"
#define PACKAGE_VERSION  "2.6.0"

/* Networking headers provided via lwIP shims in configs/wslay/ include path */
#define HAVE_ARPA_INET_H   1
#define HAVE_NETINET_IN_H  1

/* be32_to_cpu / be64_to_cpu are provided by datatypes.h via the __GNUC__
 * (__builtin_bswap32/64) path when HAVE_CONFIG_H is defined.
 * Do NOT define them here — datatypes.h defines them as static inline
 * functions and a macro here would corrupt those definitions. */

/* No OpenSSL, NSS, or WolfSSL */
/* #undef OPENSSL  */
/* #undef NSS      */
/* #undef WOLFSSL  */

#endif /* SRTP_CONFIG_H */
